### ISSUE TITLE
pyOpenSSL needs to be part of prerequisites for hosts

### ISSUE THREAD

**Issue by rwehner** [openshift/openshift-docs#1469]
`filter_plugins/oo_filters.py` now imports `OpenSSL.crypto` which is provided by the `pyOpenSSL` RPM. The [prerequisites page](https://docs.openshift.org/latest/install_config/install/prerequisites.html) should reflect this new dependency, probably as part of the step that installs `ansible`:

```
# yum -y --enablerepo=epel install ansible pyOpenSSL
```

Without the `pyOpenSSL` package, running the documented install command results in error:

```
[root@master01 openshift-ansible]# ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml
Traceback (most recent call last):
  File "/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 310, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 124, in __init__
    ds = template(basedir, ds, temp_vars)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 124, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 346, in template_from_string
    environment.filters.update(_get_filters())
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 54, in _get_filters
    plugins = [ x for x in utils.plugins.filter_loader.all()]
  File "/usr/lib/python2.7/site-packages/ansible/utils/plugins.py", line 232, in all
    self._module_cache[path] = imp.load_source('.'.join([self.package, name]), path)
  File "/root/openshift-ansible/filter_plugins/oo_filters.py", line 10, in <module>
    import OpenSSL.crypto
ImportError: No module named OpenSSL.crypto
```

**Comment by mburke5678** [comment]
This is in the docs as a prereq in:
https://docs.openshift.org/latest/install_config/install/host_preparation.html#preparing-for-advanced-installations-origin
