### ISSUE TITLE
Cannot import pyOpenSSL

### ISSUE THREAD

**Issue by sumanthreddybolledla** [openshift/openshift-docs#3940]
FAILED => Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 968, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file, delegate_host)
  File "/usr/lib/python2.6/site-packages/ansible/runner/connection.py", line 35, in connect
    conn = utils.plugins.connection_loader.get(transport, self.runner, host, port, user=user, password=password, private_key_file=private_key_file)
  File "/usr/lib/python2.6/site-packages/ansible/utils/plugins.py", line 218, in get
    self._module_cache[path] = imp.load_source('.'.join([self.package, name]), path)
  File "/usr/lib/python2.6/site-packages/ansible/runner/connection_plugins/winrm.py", line 32, in <module>
    from winrm import Response
  File "/usr/lib/python2.6/site-packages/winrm/__init__.py", line 6, in <module>
    from winrm.protocol import Protocol
  File "/usr/lib/python2.6/site-packages/winrm/protocol.py", line 11, in <module>
    from winrm.transport import Transport
  File "/usr/lib/python2.6/site-packages/winrm/transport.py", line 42, in <module>
    from requests_credssp import HttpCredSSPAuth
  File "/usr/lib/python2.6/site-packages/requests_credssp/__init__.py", line 1, in <module>
    from .credssp import HttpCredSSPAuth
  File "/usr/lib/python2.6/site-packages/requests_credssp/credssp.py", line 8, in <module>
    raise Exception("Cannot import pyOpenSSL")
Exception: Cannot import pyOpenSSL

**Comment by php-coder** [comment]
It doesn't look like documentation related issue.

**Comment by bfallonf** [comment]
@sumanthreddybolledla I'll agree with @php-coder . If there's something in the docs that's leading to problems, please let us know here. I'll close this issue, but feel free to open it again if you disagree.
