### ISSUE TITLE
asciibinder requires additional git step to work

### ISSUE THREAD

**Issue by peterroth** [openshift/openshift-docs#68268]
### Which section(s) is the issue in?
https://www.okd.io/docs/#product-documentation
The above link mentions the asciibinder can build a local version of the docs, however, it fails to start up if I use the command provided on that page:
```
$ docker run --rm -it -v `pwd`:/docs:Z quay.io/openshift-cs/asciibinder asciibinder build --distro openshift-origin
Unable to find image 'quay.io/openshift-cs/asciibinder:latest' locally
latest: Pulling from openshift-cs/asciibinder
...
Digest: sha256:5ac04d37d8b8eee9035847eaa8e75d7426e0881e562b1df7ff0f5450e8baf534
Status: Downloaded newer image for quay.io/openshift-cs/asciibinder:latest
fatal: detected dubious ownership in repository at '/docs'
To add an exception for this directory, call:

	git config --global --add safe.directory /docs
Error: Could not generate docs:
ArgumentError: '' is not a directory at
    /usr/local/bundle/gems/git-1.18.0/lib/git/base.rb:80:in `open'
    /usr/local/bundle/gems/git-1.18.0/lib/git.rb:378:in `open'
    /usr/local/bundle/gems/ascii_binder-1.2/lib/ascii_binder/engine.rb:28:in `git'
    /usr/local/bundle/gems/ascii_binder-1.2/lib/ascii_binder/engine.rb:62:in `local_branches'
    /usr/local/bundle/gems/ascii_binder-1.2/lib/ascii_binder/engine.rb:318:in `generate_docs'
    /usr/local/bundle/gems/ascii_binder-1.2/bin/asciibinder:18:in `call_generate'
    /usr/local/bundle/gems/ascii_binder-1.2/bin/asciibinder:328:in `<top (required)>'
    /usr/local/bundle/bin/asciibinder:25:in `load'
    /usr/local/bundle/bin/asciibinder:25:in `<main>'.
Try --help for help.
```
Setting `--entrypoint /bin/bash`, running the mentioned `git config` command and start the asciibinder with the options works perfectly.

### What needs fixing?
The `/docs` directory should be configured properly for building the docs.

**Comment by peterroth** [comment]
This issue is opened in the wrong repository, I'll reopen it here: https://github.com/redhataccess/ascii_binder
